ProblematicDevelopers/pullit-backend

.github/issue-branch.yml
=> ci: 깃허브 이슈 브랜치 관련 세팅

COMMON_COMPONENTS_GUIDE.md
closes #15 
---
Common-Component Document 업데이트
---
---
---
---
=> docs:Common Component document

src/main/java/com/pullit/common/embedded/StringCodeNamePair.java, src/main/java/com/pullit/item/entity/ItemMetadata.java, src/main/java/com/pullit/subject/entity/Subject.java
closes #28 
---
---
---
---
---
=> feat: Subject Entity 추가

src/main/java/com/pullit/chapter/entity/Chapter.java, src/main/java/com/pullit/subject/entity/Subject.java
closes #29 
---
---
---
---
---
=> feat: Chapter Entity 추가

src/main/java/com/pullit/common/config/SoftDeleteEntity.java, src/main/java/com/pullit/common/entity/FullAuditEntity.java, src/main/java/com/pullit/exam/entity/EvaluationDomain.java, src/main/java/com/pullit/exam/entity/Exam.java, src/main/java/com/pullit/exam/entity/ExamItem.java, src/main/java/com/pullit/exam/enums/ExamVisibility.java, src/main/java/com/pullit/item/entity/ItemActivityMapping.java
closes #33 
---
---
---
---
---
=> feat: Exam, exam_item Entity 추가

src/main/java/com/pullit/filehistory/dto/FileHistoryDTO.java, src/main/java/com/pullit/filehistory/entity/FileHistory.java, src/main/java/com/pullit/filehistory/repository/FileHistoryRepository.java
…본틀 생성
closes #45 
---
문제가공 서비스내 파일 업로드 히스토리 저장하는fileHistory DTO, Entity, Repository 기본틀 추가 
---
---
---
---
=> feat: 문제가공 서비스내 파일 업로드 히스토리 저장하는fileHistory DTO, Entity, Repository

build.gradle, src/main/java/com/pullit/common/config/QueryDslConfig.java
closes #48 
---
---
---
---
---
=> feat: queryDSL 의존성/Config 추가

src/main/java/com/pullit/cbt/entity/AttemptExam.java, src/main/java/com/pullit/cbt/entity/AttemptExamQuestion.java
closes #78 
---
attempt 관련 entitiy 추가
---
---
---
---
=> feat: attemptExam, attamptExamQuestion entity 추가

src/main/java/com/pullit/common/config/AuditorAwareImpl.java, src/main/java/com/pullit/common/validator/PasswordValidator.java, src/main/java/com/pullit/teacher/entity/Teacher.java, src/main/java/com/pullit/user/dto/request/TeacherInfo.java, src/main/java/com/pullit/user/dto/request/UserCreateRequest.java
closes #89 
---
---
---
---
---
=> feat: teacher Entity

src/main/java/com/pullit/cbt/controller/CbtController.java, src/main/java/com/pullit/cbt/dto/request/CbtAttemptRequest.java, src/main/java/com/pullit/cbt/dto/request/RedisMigrationRequest.java, src/main/java/com/pullit/cbt/dto/request/RedisUpdateRequest.java, src/main/java/com/pullit/cbt/dto/response/AttemptAnswerResponse.java, src/main/java/com/pullit/cbt/dto/response/AttemptQuestionAnswerResponse.java, src/main/java/com/pullit/cbt/dto/response/CbtAttemptResponse.java, src/main/java/com/pullit/cbt/dto/response/CbtExamItemResponse.java, src/main/java/com/pullit/cbt/dto/response/CbtExamResponse.java, src/main/java/com/pullit/cbt/dto/response/RedisDataResponse.java, src/main/java/com/pullit/cbt/dto/response/RedisMigrationResponse.java, src/main/java/com/pullit/cbt/dto/response/RedisUpdateResponse.java, src/main/java/com/pullit/cbt/repository/AttemptExamQuestionRepository.java, src/main/java/com/pullit/cbt/repository/AttemptExamRepository.java, src/main/java/com/pullit/cbt/service/CbtService.java, src/main/java/com/pullit/cbt/service/CbtServiceImpl.java, src/main/java/com/pullit/chapter/controller/ChapterController.java
closes #93
---
CBT를 생성하고 풀고 저장하는 로직
---
---
---
---
=> feat: cbt 생성, 저장, 임시 저장 등 구현

src/main/java/com/pullit/cbt/dto/request/RedisMigrationRequest.java, src/main/java/com/pullit/cbt/dto/response/CbtAttemptResponse.java, src/main/java/com/pullit/cbt/dto/response/RedisMigrationResponse.java, src/main/java/com/pullit/cbt/entity/AttemptExam.java, src/main/java/com/pullit/cbt/service/CbtServiceImpl.java
closes #107 
---
fIx: cbt 시간 저장 설정
---
---
---
---
=> fIx: cbt 시간 저장 설정

src/main/java/com/pullit/auth/controller/OAuth2AuthorizationController.java, src/main/java/com/pullit/auth/controller/OAuth2CallbackController.java, src/main/java/com/pullit/auth/dto/response/OAuth2LoginResult.java
closes #117 
---
---
---
---
---
=> feat: social login

src/main/java/com/pullit/classes/controller/SchoolController.java, src/main/java/com/pullit/classes/dto/request/SchoolRequest.java, src/main/java/com/pullit/classes/dto/response/SchoolResponse.java, src/main/java/com/pullit/classes/entity/School.java, src/main/java/com/pullit/classes/repository/SchoolRepository.java, src/main/java/com/pullit/classes/service/SchoolService.java, src/main/java/com/pullit/classes/service/SchoolServiceImpl.java, src/main/java/com/pullit/exam/service/ExamSearchServiceImpl.java, src/main/java/com/pullit/item/service/ItemSearchServiceImpl.java, src/main/java/com/pullit/teacher/entity/Teacher.java
closes #121 
---
---
---
---
---
=> feat: school

build.gradle, src/main/java/com/pullit/cbt/controller/CbtController.java, src/main/java/com/pullit/chapter/controller/ChapterController.java, src/main/java/com/pullit/classes/controller/ClassesController.java, src/main/java/com/pullit/classes/dto/response/ClassDetailResponse.java, src/main/java/com/pullit/classes/dto/response/ClassResponse.java, src/main/java/com/pullit/classes/dto/response/StudentInfoResponse.java, src/main/java/com/pullit/classes/dto/response/TeacherInfoResponse.java, src/main/java/com/pullit/classes/entity/ClassTeacher.java, src/main/java/com/pullit/classes/entity/ClassTeacherId.java, src/main/java/com/pullit/classes/entity/Classes.java, src/main/java/com/pullit/classes/repository/ClassRepository.java, src/main/java/com/pullit/classes/repository/ClassTeacherRepository.java, src/main/java/com/pullit/classes/service/ClassesService.java, src/main/java/com/pullit/classes/service/ClassesServiceImpl.java, src/main/java/com/pullit/student/repository/StudentRepository.java, src/main/java/com/pullit/teacher/entity/Teacher.java, src/main/java/com/pullit/teacher/repository/TeacherRepository.java, src/main/java/com/pullit/websocket/config/WebSocketConfig.java, src/main/java/com/pullit/websocket/dto/request/ChatMessageRequest.java, src/main/java/com/pullit/websocket/dto/request/OnlineStatusRequest.java, src/main/java/com/pullit/websocket/dto/response/ChatMessageResponse.java, src/main/java/com/pullit/websocket/dto/response/OnlineStatusResponse.java, src/main/java/com/pullit/websocket/handler/ClassChatWebSocketHandler.java, src/main/java/com/pullit/websocket/handler/WebSocketEventListener.java, src/main/java/com/pullit/websocket/service/ClassChatWebSocketService.java, src/main/java/com/pullit/websocket/service/OnlineStatusService.java
closes #125 
---
웹소켓 관련 설정 추가하였슴다
---
---
---
---
=> feat: 웹소켓 관련 기능 추가

src/main/java/com/pullit/auth/dto/response/OAuth2LoginResult.java, src/main/java/com/pullit/auth/service/OAuth2Service.java, src/main/java/com/pullit/classes/controller/SchoolController.java, src/main/java/com/pullit/classes/service/SchoolService.java, src/main/java/com/pullit/classes/service/SchoolServiceImpl.java, src/main/java/com/pullit/user/dto/request/UserCreateRequest.java, src/main/resources/application.yml
=> feat: schoolAPI

src/main/java/com/pullit/chapter/service/ChapterServiceImpl.java, src/main/java/com/pullit/common/annotation/RedisCacheEvict.java, src/main/java/com/pullit/common/aspect/RedidCacheEvictAspect.java, src/main/java/com/pullit/common/aspect/RedisCacheAspect.java, src/main/java/com/pullit/common/aspect/RedisCacheEvictAspect.java, src/main/java/com/pullit/common/cache/service/CacheInvalidationService.java, src/main/java/com/pullit/common/config/AopConfig.java, src/main/java/com/pullit/exam/service/ExamSearchServiceImpl.java, src/main/java/com/pullit/item/dao/ItemMetadataRepositoryCustom.java, src/main/java/com/pullit/item/dao/ItemMetadataRepositoryImpl.java, src/main/java/com/pullit/item/service/ItemSearchServiceImpl.java, src/main/java/com/pullit/item/service/SubjectServiceImpl.java
closes #142 
---
---
---
---
---
=> feat: Redis Cache

src/main/java/com/pullit/classes/service/ClassesServiceImpl.java, src/main/java/com/pullit/exam/dto/response/UserExamSchoolResponse.java
closes #149 
---
response에 출제자 정보 추가
---
---
---
---
=> response에 출제자 정보 추가

src/main/java/com/pullit/classes/Projection/StatsDetailProjection.java, src/main/java/com/pullit/classes/dto/response/StatsDetailResponse.java, src/main/java/com/pullit/classes/repository/StatsRepository.java
closes #148 
---
class stats detail data column added
---
---
---
---
=> class stats api 생성 수정2

src/main/java/com/pullit/classes/dto/request/LiveExamAttemptRequest.java, src/main/java/com/pullit/classes/dto/response/LiveExamAttemptResponse.java, src/main/java/com/pullit/websocket/dto/request/ExamProgressRequest.java, src/main/java/com/pullit/websocket/dto/response/ExamProgressResponse.java
closes #162 
---
---
---
---
---
=> feat: 실시간 시험 관련 기능 추가

src/main/java/com/pullit/item/elastic/controller/ItemController.java, src/main/java/com/pullit/item/elastic/service/ItemImageService.java, src/main/resources/application.yml
closes #175 
---
ES 랜덤 문항 조회 기능 추가
---
---
---
---
=> ES 랜덤 문항 조회 기능 추가

src/main/java/com/pullit/item/elastic/service/ItemImageService.java
closes #182 
---
ES 랜덤 문항 조회 수정
---
---
---
---
=> ES 랜덤 문항 조회 기능 수정

src/main/java/com/pullit/cbt/repository/ReportRepository.java
closes #185 
---
상세리포트 버그 픽스
---
---
---
---
=> 상세리포트 버그 수정

src/main/java/com/pullit/filehistory/controller/FileHistoryController.java, src/main/java/com/pullit/filehistory/service/FileHistoryServiceImpl.java, src/main/java/com/pullit/filehistory/service/PdfProcessingServiceImpl.java
closes #187 
---
잘못된 인덱스 처리 및 만료 이미지 링크 관련 수정
---
---
---
---
=> #187 bug file history pdf image not loading image

src/main/java/com/pullit/item/elastic/service/ItemImageService.java
closes #199 
---
ES 랜덤 문항 조회 로직 고도화
- 알고리즘 최적화
- 엣지 케이서 추가 처리
---
---
---
---
=> ES 랜덤 문항 조회 고도화
